export const GET_ALL_BANNER = "GET_ALL_BANNER";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const PHIM_PHAN_TRANG = "PHIM_PHAN_TRANG";
export const LAY_THONG_TIN_PHIM = "LAY_THONG_TIN_PHIM";
