export const GET_ALL_MOVIE_THEATER = "GET_ALL_MOVIE_THEATER";
export const GET_THEATER_CLUSTER = "GET_THEATER_CLUSTER";
export const LAY_THONG_TIN_LICH_CHIEU_HE_THONG =
  "LAY_THONG_TIN_LICH_CHIEU_HE_THONG";
