export const GET_ALL_BANNER = "GET_ALL_BANNER";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_MOVIE_COMMING = "GET_MOVIE_COMMING";
